### ISSUE TITLE
Downloading ghc bindist: openssl error

### ISSUE THREAD

**Issue by vu3rdd** [haskell-infra/ghc-homepage#5]
[I am not sure if this is the right place to report this, as I don't see any ghc 8.2.2 related pages in the repo. Apologies if this is not the right place. If that is the case, please point me to the right place to report errors related to ghc pages.]

I was trying to download ghc 8.2.2 binaries for osx via wget on OSX 10.10.5. The wget version is 1.16. I get the below alert on the protocol version. The download does not proceed.

```
$ wget https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-apple-darwin.tar.xz
--2017-12-05 20:29:01--  https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-apple-darwin.tar.xz
Resolving downloads.haskell.org... 151.101.0.68, 151.101.128.68, 151.101.192.68, ...
Connecting to downloads.haskell.org|151.101.0.68|:443... connected.
OpenSSL: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
Unable to establish SSL connection.
```
However, this works:

`curl -O https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-apple-darwin.tar.xz`

I have been using wget to download stuff for a long time and haven't faced problems with other websites, so I thought of reporting it here.

**Comment by hvr** [comment]
Afaik we disabled  TLS 1.0 support on most haskell.org services; so I think that's what the "tlsv1 alert protocol version" error is trying to tell you. I'd expect you'll face the same error more and more for other services on the internet, as more and more services on the Internet are slowly removing support for TLS 1.0

**Comment by thoughtpolice** [comment]
The `wget` [manual says](https://www.gnu.org/software/wget/manual/html_node/HTTPS-_0028SSL_002fTLS_0029-Options.html), regarding the `--secure-protocol` flag:

> Choose the secure protocol to be used. Legal values are ‘auto’, ‘SSLv2’, ‘SSLv3’, ‘TLSv1’, ‘TLSv1_1’, ‘TLSv1_2’ and ‘PFS’. If ‘auto’ is used, the SSL library is given the liberty of choosing the appropriate protocol automatically, **which is achieved by sending a TLSv1 greeting. This is the default.**

Thus the server implicitly rejects the TLS 1.0 greeting, I would assume. Using `--secure-protocol=TLSv1_2` to `wget` (perhaps by wrapper script, or alias) should fix this.

It's likely curl simply defaults to something more modern like TLS 1.1 when doing the negotiation.

I'm not sure whether or not this would be considered a bug in `wget` or not, since I would hope if it rejected the TLS 1.0 greeting, it would try a new one (perhaps of a higher version)...

**Comment by vu3rdd** [comment]
Thanks everyone. I forgot to mention that I tried `--secure-protocol=TLSv1_2` after reading the manpage. That gave me as output, `Abort trap: 6`. Indeed a newer version of wget fixes these errors.
